services:
  backend:
    build: ./backend
    image: yassinebenz/flask-api:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: flaskdb
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: yassinebenz/frontend-app:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
 